server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 32400
      cookie:
        max-age: 32400
        name: LoginSession
        http-only: true
        secure: true
  error:
    whitelabel:
      enabled: true

logging:
  file:
    name: logs/melub.log
    rollingpolicy: DailyRollingFileAppender
    pattern: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
  level:
    root: INFO

spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://(IP):(PORT)/(테이블명)?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: 계정명
    password: 비밀번호
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
